---
.travis.yml:
  forge_password: "iCG7BQIl50ghxfKnAi65BNiBAFM6wB4xPWbgyvE+AplePyG05CBEuzQIMniI13Nvl3Py3aoV86Uv35zWoU43D0pCqRp7pNyKVnMkQW7TiNxjwr6ZHgi5Y2JdiA5up1Cvhzd4J5J0SzKX0TPmL/quTkgAdrHIuYjAMxuwGaIVYlQ="
