name         'camptocamp-logstash'
version      '0.0.1'
dependency   'ripienaar/concat', '>= 0.2.0'
source       'https://github.com/camptocamp/puppet-logstash'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp Logstash Module'
description  'Logstash Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-logstash'
