name         'camptocamp-logstash'
version      '0.1.0'
dependency   'puppetlabs/stdlib', '>= 2.2.1'
dependency   'ripienaar/concat', '>= 0.2.0'
source       'https://github.com/camptocamp/puppet-logstash'
author       'DevOps Team / Camptocamp'
license      'Apache 2.0'
summary      'Camptocamp Logstash Module'
description  'Puppet module for Logstash'
project_page 'https://github.com/camptocamp/puppet-logstash'
